Repository MatheusIMPACTA/devops-aula07, pull requests merged in 2018-09, with the labels that each got.

#2 commit one
  docs/Requisitos.md
Labels: Análise

#18 programação v1.1
  README.md
Labels: Programação

#19 arquitetura v1.1
  docs/Requisitos.md
Labels: Análise

#20 Alt
  README.md
Labels: Análise

#21 testes da implementação v1.1
  README.md
Labels: testes

#22 Gerar Release v1.1
  README.md
  docs/Requisitos.md
Labels: operações
